### ISSUE TITLE
v2.0.0 Checklist

### ISSUE THREAD

**Issue by chaitanya1731** [intel/intel-data-center-gpu-driver-for-openshift#65]
Includes **OOT Intel GPU driver release for RHOCP 4.13.10**
Checklist:
- [x] Update dockerfile with the latest driver release - [I915_23WW39.5_682.38_23.6.37_230425.49](https://github.com/intel-gpu/intel-gpu-i915-backports/releases/tag/I915_23WW39.5_682.38_23.6.37_230425.49)
- [x] Build and validate driver container for 4.13.10 OCP using KMM
- [x] Driver signing
- [x] Update release notes, root readme (if required), release readme table
- [x] Preflight certification scanning and publish image on RH catalog
- [x] Cut release on github

**Comment by chaitanya1731** [comment]
Published v2.0.0 Driver Container.. 
RH catalog - https://catalog.redhat.com/software/containers/intel/intel-data-center-gpu-driver-container/6495ee55c8b2461e35fb8264?tag=2.0.0-5.14.0-284.28.1.el9_2.x86_64 
Release - https://github.com/intel/intel-data-center-gpu-driver-for-openshift/releases/tag/v2.0.0
