### ISSUE TITLE
v2.1.0 Release Checklist

### ISSUE THREAD

**Issue by chaitanya1731** [intel/intel-data-center-gpu-driver-for-openshift#74]
Includes **OOT Intel GPU driver release for RHOCP 4.14.0 and above**
Checklist:

- [x]  Update dockerfile with the latest driver release - [I915_23WW51.5_682.48_23.6.42_230425.56](https://github.com/intel-gpu/intel-gpu-i915-backports/releases/tag/I915_23WW51.5_682.48_23.6.42_230425.56). Release Notes [here](https://dgpu-docs.intel.com/releases/production_682.48_20231219.html)
- [x]  Build and validate driver container for 4.14.0 OCP using KMM
- [x]  Driver signing
- [x]  Update release notes, root readme (if required), release readme table
- [x]  Preflight certification scanning and publish image on RH catalog
- [x]  Cut release on github

**Comment by chaitanya1731** [comment]
released - https://github.com/intel/intel-data-center-gpu-driver-for-openshift/releases/tag/v2.1.0
